paths:
  train_data: data/train
  test_data: data/test
  casestudy_data: data/casestudy
  pretrained_models: models/pretrained
  checkpoints: models/checkpoints
  runs: runs
simulation:
  Lx: 0.1
  Ly: 0.05
  Nx: 255
  Ny: 127
  dt: 3.0e-08
  N: 2000
  gamma0: 1.0e-05
  rho: 2700
  c: 6000
  numberOfSources: 4
  distanceBetweenSources: 36
  distanceBetweenSensors: 6
source:
  frequency: 500000
  cycles: 2
  amplitude: 1000000000000.0
data_generation:
  seed: 2
  train:
    number_of_cases: 5
    number_of_damages: 1
    factor_to_avoid_inverse_crime: 2
  test:
    number_of_cases: 2
    number_of_damages: 1
    factor_to_avoid_inverse_crime: 2
models:
  unet:
    channels:
    - 1
    - 16
    - 32
    - 64
    - 128
    number_of_convolutions_per_block: 2
    batch_norm: true
pretraining:
  seed: 30
  split_seed: 2
  numberOfSamples: 800
  availableSamples: 800
  trainingType: supervised
  model_type: Unet
  NNchannels:
  - 1
  - 16
  - 32
  - 64
  - 128
  numberOfConvolutionsPerBlock: 2
  batchDivisor: 10
  lr: 0.0005
  alpha: -0.5
  beta: 0.2
  epochs: 100
  clipGrad: 0.0005
  l2: 1.0e-06
  costScaling: 100000000.0
experiments:
  cases:
  - 1
  - 2
  - 3
  - 4
  pretrain_samples:
  - 800
  epochs_pretrain: 100
  modelType: Unet
  NNchannels:
  - 1
  - 16
  - 32
  - 64
  - 128
  numberOfConvolutionsPerBlock: 2
  conventional_fwi:
    lr: 0.08
    alpha: 0.0
    beta: 0.0
    weightLrFactor: 1
    clipGrad: 1.0e-05
    epochs: 35
    costScaling: 1000000000000.0
  conventional_fwi_initial_guess:
    seed: 99
    pretrain_samples: 800
    lr: 0.05
    alpha: 0.0
    beta: 0.0
    weightLrFactor: 1
    clipGrad: 1.0e-05
    epochs: 35
    costScaling: 1000000000000.0
  nn_based_fwi:
    seed: 50
    input_shape:
    - 1
    - 128
    - 8
    - 4
    trunc_normal_mean: 0.4
    trunc_normal_std: 0.2
    trunc_normal_a: 0.0
    trunc_normal_b: 0.9
    lr: 0.0005
    alpha: -0.5
    beta: 0.2
    epochs: 35
    l2: 1.0e-06
    costScaling: 1000000000.0
  inr_fwi:
    seed: 50
    hidden_features: 128
    hidden_layers: 4
    lr: 0.0001
    alpha: -0.5
    beta: 0.2
    epochs: 35
    l2: 1.0e-06
    costScaling: 1000000000.0
  inr_siren_fwi:
    seed: 50
    hidden_features: 128
    hidden_layers: 4
    omega0: 30.0
    lr: 3.0e-05
    alpha: -0.5
    beta: 0.2
    epochs: 35
    l2: 1.0e-06
    costScaling: 1000000000.0
  transfer_learning_fwi:
    seed: 99
    lr: 0.0005
    alpha: -0.5
    beta: 0.2
    epochs: 5
    clipGrad: 5.0e-05
    l2: 1.0e-06
    costScaling: 10000000000.0
  transfer_learning_fwi_frozen_encoder:
    seed: 99
    lr: 0.0005
    alpha: -0.5
    beta: 0.2
    epochs: 5
    clipGrad: 5.0e-05
    l2: 1.0e-06
    costScaling: 10000000000.0
