paths:
  train_data: data/debug_train
  test_data: data/debug_test
  casestudy_data: data/casestudy
  pretrained_models: models/pretrained
  checkpoints: models/checkpoints
  runs: runs

simulation:
  Lx: 0.1
  Ly: 0.05
  Nx: 63
  Ny: 31
  dt: 3.0e-08
  N: 200
  gamma0: 1.0e-05
  rho: 2700
  c: 6000
  numberOfSources: 4
  distanceBetweenSources: 8
  distanceBetweenSensors: 4

source:
  frequency: 500000
  cycles: 2
  amplitude: 1.0e+12

data_generation:
  seed: 2
  train:
    number_of_cases: 1
    number_of_damages: 1
    factor_to_avoid_inverse_crime: 2
  test:
    number_of_cases: 2
    number_of_damages: 1
    factor_to_avoid_inverse_crime: 2

models:
  unet:
    channels: [1, 16, 32, 64, 128]
    number_of_convolutions_per_block: 2
    batch_norm: true

pretraining:
  seed: 30
  split_seed: 2
  numberOfSamples: 1
  availableSamples: 1
  trainingType: supervised
  model_type: Unet
  NNchannels: [1, 16, 32, 64, 128]
  numberOfConvolutionsPerBlock: 2
  batchDivisor: 1
  lr: 5.0e-04
  alpha: -0.5
  beta: 0.2
  epochs: 1
  clipGrad: 5.0e-04
  l2: 1.0e-06
  costScaling: 1.0e+08

experiments:
  cases: [1]
  pretrain_samples: [800]
  epochs_pretrain: 100
  modelType: Unet
  NNchannels: [1, 16, 32, 64, 128]
  numberOfConvolutionsPerBlock: 2

  conventional_fwi:
    lr: 8.0e-02
    alpha: 0.0
    beta: 0.0
    weightLrFactor: 1
    clipGrad: 1.0e-05
    epochs: 1
    costScaling: 1.0e+12

  conventional_fwi_initial_guess:
    seed: 99
    pretrain_samples: 800
    lr: 5.0e-02
    alpha: 0.0
    beta: 0.0
    weightLrFactor: 1
    clipGrad: 1.0e-05
    epochs: 1
    costScaling: 1.0e+12

  nn_based_fwi:
    seed: 50
    input_shape: [1, 128, 8, 4]
    trunc_normal_mean: 0.4
    trunc_normal_std: 0.2
    trunc_normal_a: 0.0
    trunc_normal_b: 0.9
    lr: 5.0e-04
    alpha: -0.5
    beta: 0.2
    epochs: 1
    clipGrad: 5.0e-05
    l2: 1.0e-06
    costScaling: 1.0e+09

  inr_fwi:
    seed: 50
    hidden_features: 128
    hidden_layers: 4
    output_mode: voidness
    final_bias: -5.0
    lr: 1.0e-04
    alpha: -0.5
    beta: 0.2
    epochs: 1
    clipGrad: 5.0e-05
    tv_weight: 0.0
    tv_type: anisotropic
    l2: 1.0e-06
    costScaling: 1.0e+09

  inr_siren_fwi:
    seed: 50
    hidden_features: 128
    hidden_layers: 4
    omega0: 30
    output_mode: voidness
    final_bias: -5.0
    lr: 1.0e-04
    alpha: -0.5
    beta: 0.2
    epochs: 1
    clipGrad: 5.0e-05
    tv_weight: 0.0
    tv_type: anisotropic
    l2: 1.0e-06
    costScaling: 1.0e+09

  inr_lr_fwi:
    seed: 50
    rank: 8
    hidden_features: 128
    hidden_layers: 3
    omega0: 30
    core_init_std: 1.0e-03
    output_mode: voidness
    final_bias: -5.0
    lr: 1.0e-04
    alpha: -0.5
    beta: 0.2
    epochs: 1
    tv_weight: 0.0
    tv_type: anisotropic
    l2: 1.0e-06
    costScaling: 1.0e+09

  inr_mpe_fwi:
    seed: 50
    num_levels: 4
    base_resolution: 16
    per_level_scale: 1.2
    features_per_level: 2
    hidden_features: 64
    hidden_layers: 2
    grid_init_std: 1.0e-04
    align_corners: true
    swap_grid_coords: false
    output_mode: voidness
    final_bias: -5.0
    lr: 1.0e-04
    alpha: -0.5
    beta: 0.2
    epochs: 1
    tv_weight: 0.0
    tv_type: anisotropic
    l2: 1.0e-06
    costScaling: 1.0e+09

  inr_mpe_centered_fwi:
    seed: 50
    num_levels: 4
    base_resolution: 16
    per_level_scale: 1.2
    features_per_level: 2
    hidden_features: 64
    hidden_layers: 2
    grid_init_std: 1.0e-04
    align_corners: true
    swap_grid_coords: false
    output_mode: voidness
    final_bias: -5.0
    lr: 1.0e-04
    alpha: -0.5
    beta: 0.2
    epochs: 1
    tv_weight: 0.0
    tv_type: anisotropic
    l2: 1.0e-06
    costScaling: 1.0e+09

  inr_ig_fwi:
    seed: 50
    fusion_alpha: 0.5
    num_levels: 4
    base_resolution: 16
    per_level_scale: 1.2
    features_per_level: 2
    grid_init_std: 1.0e-04
    align_corners: true
    swap_grid_coords: false
    siren_hidden_features: 128
    siren_hidden_layers: 2
    siren_out_features: 128
    omega0: 30
    fusion_hidden_features: 64
    fusion_hidden_layers: 2
    output_mode: voidness
    final_bias: -5.0
    lr: 1.0e-04
    alpha: -0.5
    beta: 0.2
    epochs: 1
    tv_weight: 0.0
    tv_type: anisotropic
    l2: 1.0e-06
    costScaling: 1.0e+09

  inr_ig_centered_fwi:
    seed: 50
    fusion_alpha: 0.5
    num_levels: 4
    base_resolution: 16
    per_level_scale: 1.2
    features_per_level: 2
    grid_init_std: 1.0e-04
    align_corners: true
    swap_grid_coords: false
    siren_hidden_features: 128
    siren_hidden_layers: 2
    siren_out_features: 128
    omega0: 30
    fusion_hidden_features: 64
    fusion_hidden_layers: 2
    output_mode: voidness
    final_bias: -5.0
    lr: 1.0e-04
    alpha: -0.5
    beta: 0.2
    epochs: 1
    tv_weight: 0.0
    tv_type: anisotropic
    l2: 1.0e-06
    costScaling: 1.0e+09

  transfer_learning_fwi:
    seed: 99
    lr: 5.0e-04
    alpha: -0.5
    beta: 0.2
    epochs: 1
    clipGrad: 5.0e-05
    l2: 1.0e-06
    costScaling: 1.0e+10

  transfer_learning_fwi_frozen_encoder:
    seed: 99
    lr: 5.0e-04
    alpha: -0.5
    beta: 0.2
    epochs: 1
    clipGrad: 5.0e-05
    l2: 1.0e-06
    costScaling: 1.0e+10
